feh --bg-scale --randomize $HOME/.local/share/wallpapers/ &
wmname "LG3D" &
# export _JAVA_AWT_WM_NONREPARENTING=1
eval $(gnome-keyring-daemon --start) &
export SSH_AUTH_SOCK &
xset -dpms &
exec slstatus &
exec /usr/libexec/polkit-gnome-authentication-agent-1 &
exec nm-applet &
exec picom &
exec dbus-launch --sh-syntax --exit-with-session dwm
